language: php
dist: xenial

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=0

matrix:
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

before_install:
  # Speed up build time by disabling Xdebug.
  # @link https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  # @link https://twitter.com/kelunik/status/954242454676475904
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer install

script: phpunit
