language: php
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.8 WP_MULTISITE=0

matrix:
  fast_finish: true

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

install:
  - composer install

script: phpunit
